// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA61XzT7r6XBQtq8ZkYQn3Z4qBGnCwGwWc',
    appId: '1:944085067908:web:1234567890abcdef',
    messagingSenderId: '944085067908',
    projectId: 'moviediary-e9a38',
    authDomain: 'moviediary-e9a38.firebaseapp.com',
    databaseURL: 'https://moviediary-e9a38-default-rtdb.firebaseio.com',
    storageBucket: 'moviediary-e9a38.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA61XzT7r6XBQtq8ZkYQn3Z4qBGnCwGwWc',
    appId: '1:944085067908:android:1234567890abcdef',
    messagingSenderId: '944085067908',
    projectId: 'moviediary-e9a38',
    databaseURL: 'https://moviediary-e9a38-default-rtdb.firebaseio.com',
    storageBucket: 'moviediary-e9a38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA61XzT7r6XBQtq8ZkYQn3Z4qBGnCwGwWc',
    appId: '1:944085067908:ios:e752583198be968657fad1',
    messagingSenderId: '944085067908',
    projectId: 'moviediary-e9a38',
    databaseURL: 'https://moviediary-e9a38-default-rtdb.firebaseio.com',
    storageBucket: 'moviediary-e9a38.firebasestorage.app',
    iosBundleId: 'com.example.movivi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA61XzT7r6XBQtq8ZkYQn3Z4qBGnCwGwWc',
    appId: '1:944085067908:ios:e752583198be968657fad1',
    messagingSenderId: '944085067908',
    projectId: 'moviediary-e9a38',
    databaseURL: 'https://moviediary-e9a38-default-rtdb.firebaseio.com',
    storageBucket: 'moviediary-e9a38.firebasestorage.app',
    iosBundleId: 'com.example.movivi',
  );
}
